FROM rust:1.73.0 as builder

WORKDIR /app

COPY . .

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends protobuf-compiler \
 && rm -rf /var/lib/apt/lists/*

RUN cargo build --release

FROM rust:1.73.0
COPY --from=builder /app/target/release/client /usr/local/bin/client

CMD ["sh", "-c", "client"]